--liquibase formatted sql

--changeset agrat:1
CREATE TABLE USER_REQUEST (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(255) UNIQUE NOT NULL,
    counter INT,
    PRIMARY KEY(id)
);
-- rollback DROP TABLE USER_REQUEST;